services:
  clickhouse:
    image: clickhouse:24.9
    volumes:
      - "clickhouse-vol:/var/lib/clickhouse"
    ports:
      - "18123:8123"
      - "19000:9000"
    networks:
      - db_network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.3.1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  init-kafka:
    image: confluentinc/cp-kafka:7.3.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics --bootstrap-server kafka:9092 --list
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic topic1 --replication-factor 1 --partitions 1
      "
  kafka-ui:
    container_name: playground-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8089:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'

networks:
  db_network:
volumes:
  clickhouse-vol: